#include <TFile.h>
#include <TTree.h>


Int_t brunid;
Int_t beventid;
Float_t bVz;
Float_t bVzerr;
Int_t brefmult;
Int_t btofmult;
Int_t countrefmult;
Double_t refmultcor;
Double_t reweight;
Int_t cent9;
Int_t bparticleid;
Float_t bparticlemass;
Float_t bpx;
Float_t bpy;
Float_t bpz;
Float_t bpl;
Float_t chi2primary_he;
Float_t chi2primary_pi;
Float_t dca_he;
Float_t dca_pi;
Float_t ht_ldl;
Float_t ht_dl;
Float_t ht_l;
Float_t ht_chi2topo;
Float_t ht_chi2ndf;
Int_t nhits_he;
Int_t nhits_pi;
Int_t nhitsdedx_he;
Int_t nhitsdedx_pi;
Float_t dedx_he;
Float_t dedx_pi;
Float_t ht_chi2;
Float_t ht_NDF;
Float_t ht_bdfvtx;
Float_t ht_bdfvtx2;
Float_t ht_lifetime;
Float_t px_pi;
Float_t py_pi;
Float_t pz_pi;
Float_t px_he;
Float_t py_he;
Float_t pz_he;
Int_t bismc;
Float_t bmcpx;
Float_t bmcpy;
Float_t bmcpz;
Float_t bmcl;
Float_t bmcpl;
Int_t FXTMult2;

